add_rules("mode.debug", "mode.release")
set_languages("c++11")
set_policy("build.sanitizer.address", true)
add_links("ncurses")
add_requires("ncurses")
add_defines("ENABLE_DRIBBLE")

target("libe2")
    set_kind("static")
    add_files("movemnt.cc")
    add_files("line.cc")
    add_files("pos.cc")
    add_files("search.cc")
    add_files("mark.cc")
    add_files("cursor.cc")
    add_files("eb.cc")

target("e2")
    set_kind("binary")
    add_files("e2.cc")
    add_deps("libe2")

target("keyscan")
    set_kind("binary")
    add_files("keyscan.cc")
    add_deps("libe2")

